name: Node test
run-name: ${{ github.actor }} We are testing Github Action with Node.js

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dad-jokes package globally
        run: npm install --global @mikemcbride/dad-jokes

      - name: Display a dad joke
        run: dad-jokes > dad-joke.txt && git config user.email "github-actions[bot]" && git config user.name "github-actions[bot]@users.noreply.github.com" && git checkout -b dev && git add dad-joke.txt && git commit -m "${{github.event_name}}-by-${{github.actor}}" && git push origin dev --force
